name: update
on:   
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *' #每日更新
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest #运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7 #v3
      - name: 'Install requirements'
        run: pip install wget
             pip install bs4  #安装依赖
      - name: 'Working'
        run: 
          python update.py #运行主程序
      - name: Commit files
        run: |
          git pull
          git config --local user.email "hyh20060327@qq.com"
          git config --local user.name "RavelloH"
          git add .
          git commit -m "`date '+%Y-%m-%d %H:%M:%S'`" #动态提交信息
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes #推送
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
